### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by 0xMashiro** [Ricechips/centos7-kvm-win10#1]
@Ricechips  You can creat a repor named `work-notes` or similar. Then put all notes and thought in **Issues** and find  the time to write down some blogs. You can add tags to your issues which are are good for tracking the status of your projects.

**Comment by Ricechips** [comment]
thanks for the suggestion,I'll think about it very carefully and take action.

> @Ricechips You can creat a repor named `work-notes` or similar. Then put all notes and thought in **Issues** and find the time to write down some blogs. You can add tags to your issues which are are good for tracking the status of your projects.
